### ISSUE TITLE
nit: X-Forwarded-For

### ISSUE THREAD

**Issue by Habbie** [raybellis/draft-bellis-dnsop-xpf#4]
The HTTP header we are emulating is called X-Forwarded-For, not X-Proxied-For. Unsure we need to do anything with this insight.

**Comment by raybellis** [comment]
I'd like to leave it as XPF, since "Forwarder" has a more specific meaning in DNS that it does in HTTP (specifically, a forwarder is usually something that a resolver configures to handle _outbound_ queries) whereas this specification is intended for use on devices that sit on the _inbound_ path of a server.
